### ISSUE TITLE
Deployable on Firebase?

### ISSUE THREAD

**Issue by DM164** [vercel/hazel#112]
Does anyone know if there is a way to deploy hazel on Firebase? I really love the way it works but I don't like hosting it on Now.
Even just a link to a tutorial or a documentation would be appreciated.

**Comment by sagarsoni7** [comment]
+1

**Comment by sagarsoni7** [comment]
@DM164 https://gist.github.com/sagarsoni7/92bd8caea143ddeedbf4daff35d9d8fa

**Comment by DM164** [comment]
@sagarsoni7 Thanks 👍
