### ISSUE TITLE
Unable to Deploy with Private Repo

### ISSUE THREAD

**Issue by jackcooper04** [vercel/hazel#113]
I am getting this error after trying to deploy using a private repo
```
{
"error": {
"code": "missing_configuration_properties",
"message": "Neither NOW_URL, nor URL are defined, which are mandatory for private repo mode"
}
}
```

When I deployed it I used 
```
vercel -e ACCOUNT="<account>" -e REPOSITORY="<repo>" -e TOKEN="<token>"
```
Am I missing something?

**Comment by leo** [comment]
Fixed! Cutting a release in the next few minutes.

**Comment by tarikhaiga** [comment]
@jackcooper04 did the release by @leo workout for you at the end? Were you able to make autoupdates work with your private repo?

I've been stuck for sometime on how to make it work, would appreciate some input!
