### ISSUE TITLE
When hazel works with express.js

### ISSUE THREAD

**Issue by dalbodeule** [vercel/hazel#48]
I want to use hazel with express.js. But when I use it with express.js I do not know how to pass the necessary variables (eg repository or username). Can you tell me what to do?

**Comment by safinn** [comment]
You need to include `REPOSITORY` and `ACCOUNT` environment variables to define which repository to get releases from.

**Comment by sagarsoni7** [comment]
@dalbodeule 
```
app.get("*", (req, res) => {
  hazel({
    account: "account_name",
    repository: "repo_name",
  })(req, res);
});
```
