### ISSUE TITLE
Depreciated under v2

### ISSUE THREAD

**Issue by styks1987** [vercel/hazel#49]
`now -V 1 zeit/hazel`

**Comment by safinn** [comment]
Solved by https://github.com/zeit/hazel/pull/54

**Comment by hermes-project-software** [comment]
albeit it does seem that one needs to append `-e URL=NOW_URL` to any deploy as it does not _automatically_ resolve the url

**Comment by leo** [comment]
Fixed! Cutting a new release shortly.
