### ISSUE TITLE
Deploy to zeit now requires "-e URL=NOW_URL"

### ISSUE THREAD

**Issue by hermes-project-software** [vercel/hazel#57]
I found that deploying without setting `-e URL=NOW_URL` leaves hazel in a fritz. 

`{"error":{"code":"missing_configuration_properties","message":"Neither NOW_URL, nor URL are defined, which are mandatory for private repo mode"}}`

https://hazel-e8w92zpdf.now.sh/

**Comment by hermes-project-software** [comment]
Deploying with the code works! Maybe we should update the docs?

**Comment by kucaykojek** [comment]
Same issue here.

**Comment by euroclydon37** [comment]
The real problem is that `NOW_URL` isn't being set for some reason. @kucaykojek's solution didn't work for me because I was getting back a download url of
```
"https://api.github.com/repos/<user>/<repo>/releases?access_token=<token>/download/darwin"
```
Which obviously doesn't work. It's _trying_ to give me this.
```
https://<NOW_URL>/download/darwin
```

**Comment by leo** [comment]
Fixed! Cutting a release in the next few minutes.
